---
version: '3.3'
services:
  redis:
    container_name: redis
    image: redis:5.0-rc
  vahter:
    build: .
    image: vahter-bot:0.0.2
    container_name: vahter-bot
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    links:
      - redis
    depends_on:
      - redis
