---
version: '3.3'
services:
  redis:
    container_name: redis
    image: redis:5.0-rc
  vahter:
    build:
      context: ../
      args:
        PROJECT_PATH: github.com/novitoll/novitoll_daemon_bot
    image: vahter-bot:0.0.3
    container_name: vahter-bot
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    links:
      - redis
      - telegrammock
    depends_on:
      - redis
  telegrammock:
    build:
      context: ../../telegram-mock
    image: telegrammock
    container_name: telegrammock
